# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 01:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reguistros',
            name='estudiante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to='servicio.Personas'),
        ),
        migrations.AlterField(
            model_name='reguistros',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to='servicio.Personas'),
        ),
    ]
