# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_auto_20160120_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personas',
            name='estado',
        ),
        migrations.AddField(
            model_name='reguistros',
            name='estado',
            field=models.CharField(blank=True, choices=[('1', 'Reguistrado'), ('2', 'Asignado'), ('3', 'Culminado')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='personas',
            name='tipo',
            field=models.CharField(blank=True, choices=[('1', 'Profesor'), ('2', 'Alumno')], max_length=2, null=True),
        ),
    ]
