# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0003_auto_20160120_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reguistros',
            name='escuela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicio.Escuelas'),
        ),
    ]
