# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0006_auto_20160120_1312'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Escuelas',
            new_name='Instituciones',
        ),
    ]
