# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0007_auto_20160120_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reguistros',
            old_name='escuela',
            new_name='intitucion',
        ),
    ]
