# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0008_auto_20160120_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='telefono',
        ),
        migrations.AddField(
            model_name='alumnos',
            name='apellidos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='nombres',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='telefono1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='telefono2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reguistros',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.Alumnos'),
        ),
    ]
