# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0011_instituciones_cupos'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituciones',
            name='cupos_disponibles',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
