# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0012_instituciones_cupos_disponibles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reguistros',
            new_name='Registros',
        ),
        migrations.AlterModelTable(
            name='registros',
            table='registros',
        ),
    ]
