# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0013_auto_20160124_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='registros',
            name='fecha_de_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registros',
            name='fecha_de_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
