# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0016_auto_20160124_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=50)),
                ('fecha_de_inicio', models.DateField()),
                ('fecha_de_fin', models.DateField()),
            ],
            options={
                'db_table': 'Perido',
            },
        ),
        migrations.CreateModel(
            name='ProfesoresByIntituciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.Instituciones')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.Perido')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.Profesores')),
            ],
            options={
                'db_table': 'profesores_by_intituciones',
            },
        ),
        migrations.AlterField(
            model_name='registros',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicio.ProfesoresByIntituciones'),
        ),
    ]
