# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0017_auto_20160128_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registros',
            name='periodo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='servicio.Perido'),
            preserve_default=False,
        ),
    ]
