# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0019_auto_20160128_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicio.Perido'),
        ),
    ]
