# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0022_auto_20161003_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registros',
            name='tutor',
        ),
    ]
