# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0024_registros_tutor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registros',
            old_name='intitucion',
            new_name='institucion',
        ),
    ]
