# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-10-04 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0025_auto_20161003_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupos', models.IntegerField()),
            ],
            options={
                'db_table': 'cupos',
                'verbose_name_plural': 'Cupos',
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'facultad',
                'verbose_name_plural': 'Facultades',
            },
        ),
        migrations.AlterModelOptions(
            name='alumnos',
            options={'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AlterModelOptions(
            name='instituciones',
            options={'verbose_name_plural': 'Instituciones'},
        ),
        migrations.AlterModelOptions(
            name='perido',
            options={'verbose_name_plural': 'Periodos'},
        ),
        migrations.AlterModelOptions(
            name='profesores',
            options={'verbose_name_plural': 'Profesores'},
        ),
        migrations.AlterModelOptions(
            name='profesoresbyintituciones',
            options={'verbose_name_plural': 'Profesors Asignados a Instituciones'},
        ),
        migrations.AlterModelOptions(
            name='registros',
            options={'verbose_name_plural': 'Registros'},
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='instituciones',
            name='cupos',
        ),
        migrations.RemoveField(
            model_name='instituciones',
            name='cupos_disponibles',
        ),
        migrations.AddField(
            model_name='cupos',
            name='facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.Facultad'),
        ),
        migrations.AddField(
            model_name='cupos',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.Instituciones'),
        ),
        migrations.AddField(
            model_name='cupos',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.Perido'),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='facultad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicio.Facultad'),
        ),
    ]
