# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0026_auto_20161004_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituciones',
            name='numeros_de_beneficiarios',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
