# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0027_instituciones_numeros_de_beneficiarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituciones',
            name='numeros_de_beneficiarios',
        ),
        migrations.AddField(
            model_name='registros',
            name='numeros_de_beneficiarios',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
